version: 2.1

orbs:
  codacy: codacy/base@2.7.0
  codacy_plugins_test: codacy/plugins-test@0.10.3

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: test_and_coverage
          persist_to_workspace: true
          cmd: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install v8.11.3
            nvm alias default v8.11.3

            npm install
            export PATH=$PATH:$(pwd)/node_modules/.bin
            STYLELINT_CONFIG_BASEDIR=$(pwd)/node_modules sbt "set scalafmtUseIvy in ThisBuild := false;
                 scalafmt::test;
                 test:scalafmt::test;
                 sbt:scalafmt::test;
                 coverage;
                 test;
                 coverageReport;
                 coverageAggregate"
            bash <(curl -Ls https://coverage.codacy.com/get.sh)
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: publish_docker_local
          cmd: |
            sbt "runMain codacy.stylelint.DocGenerator"
            docker build -t codacy-stylelint-base .
            sbt "set scalafmtUseIvy in ThisBuild := false;
                 set version in Docker := \"latest\";
                 docker:publishLocal"
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - test_and_coverage
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - codacy/publish_docker
